# Generated by Django 5.1.6 on 2025-02-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyectos', '0002_alter_proyecto_usuarios'),
        ('UsersAutentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('tarea', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('sin_empezar', 'Sin empezar'), ('en_proceso', 'En proceso'), ('finalizada', 'Finalizada')], max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_del_proyecto', to='Proyectos.proyecto')),
                ('usuarios_asignados', models.ManyToManyField(related_name='tareas_asignadas_usuario', to='UsersAutentication.usuario')),
            ],
        ),
    ]
