# Generated by Django 5.1.6 on 2025-02-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_alter_proyecto_usuarios'),
        ('Tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tareas',
            field=models.ManyToManyField(related_name='proyectos_asociados', to='Tareas.tarea'),
        ),
    ]
